### PR TITLE
[WIP] Code Jam API

### LINKED ISSUE #22: Code Jam API
Implement an API which can manage code-jams!

| Endpoint | Method | Description |
| --- | --- | --- |
| /api/codejam | GET | Retrieve a list of code jams |
| /api/codejam/{id} | DELETE | Delete a codejam (if system admin) |
| /api/codejam/{id} | POST | Edit codejam (if system admin) |
| /api/codejam/categories | GET | Retrieve all code-jam categories |
| /api/codejam/category | POST | create a new category (if system admin) |
| /api/codejam/category/{id} | DELETE | Delete a category (if system admin) |
| /api/codejam/category/{id} | POST | Modify category (if system admin) |
| /api/codejam?category={category} | GET | Retrieve codejams under a specific category |
| /api/codejam/{codejamid}/register | POST | Register currently logged in user into codejam with `codejamid` |
| /api/codejam/{codejamid}/withdraw | POST | Remove currently logged in user from codejam with `codejamid` |
| /api/codejam/{codejamid}/submit-project | POST |  Save submitted project information for currently logged in user for codejam with `codejamid` |
| /api/codejam/admin | GET | Locked for admins only - show all the things |

There might be a few more api endpoints introduced based on administrative requirements / needs as this gets flushed out.

In a nut shell we should be able to have administrators create codejams. 
Any authenticated user should be able register for a codejam. 

# Code Jam Information
1. Id
2. Title
3. Description
4. Category
5. JamStartDate (time in which the jam is actually running)
6. JamEndDate (time in which the jam ends. Submissions are closed at this time)
7. RegistrationStartDate (time in which users can start registering)
8. RegistrationEndDate (time in which users are no longer able to register

# Registration Information
1. Id
2. UserId (the ID of the user who is trying to register)
3. CodeJamId (the ID of the codejam record they're registering for)
4. Timezone (the Timezone they're going to try participating in)
5. PreferTeam (a boolean value which indicates if this user wants to be on a team, or go at it solo)

# Code Jam Team Information
1. Id
2. Team Name
3. Team Logo (Think this should be a url?)

# Code Jam Team Member Information
1. Id
2. TeamId  (id of the team we're tying this relationship to)
5. UserId (id of the user we're tying this relationship to)

# Code Jam Submission
Idea here is that we get to reuse the same model to cover the archetype of "Team submission" versus "Solo Submission".
At no point should both the team AND user id be null. A minimum of one of those is required to be provided.

1. Id
2. Team Id (nullable)
3. User Id (nullable) 
4. RepoUrl
5. SubmittedOn (date time)

# Code Jam Submission Review 
IDK about the name but the idea here is that those with the appropriate role(s) should be able to review a submission and leave comments / grades

1. Id
2. UserId
3. SubmissionId
4. Data (JSON format? Probably the best considering reviews could change format overtime? or dynamic fields?)
6. DateTime - for timekeeping sake

### PR DESCRIPTION
**Pull request by JBraunsmaJr**
This PR is a WIP.

Implements #22 

# Showcase
image

Closes #22

### CODE REVIEW

**Comment by JBraunsmaJr** [comment]
image

- Added a culture selector on the top right of appbar (we don't have a profile page/menu setup yet so this spot works for now?)
- Added Time Utility. Allows us to grab the timezone offset from the browser and apply that to whichever datetime value we want to view as "local time"

This will require standardization of all datetimes to use UTC. When displaying we can convert to local time using the new extension method.

**Comment by JBraunsmaJr** [comment]
image

Working on adding additional information to topic cards.

- Total solo applicants
- Total team applicants
- Ability to Withdraw (if already registered)
- Ability to register (if not registered)

**Comment by JBraunsmaJr** [comment]
- Added popover

When a user has not registered for a topic they'll see the register button as depicted below. We only have 1 parameter needed when registering (do you want to be on a team or be solo). Clicking the register button will bring up a popover menu with 2 icons that correlate to solo / team. Clicking one of those icons will send the appropriate request to register you.

image
image
image

**Review by willj4945 — CHANGES_REQUESTED** [review]
Maybe add a bit of padding between Heading Topic 0,1,2,4 etc. Seems a bit bunched up with the picture. Thoughts? 

Padding issue

**Comment by JBraunsmaJr** [comment]
> Maybe add a bit of padding between Heading Topic 0,1,2,4 etc. Seems a bit bunched up with the picture. Thoughts?
> 
> Padding issue

Good call, shall add a smidge of padding in the next push

**Comment by JBraunsmaJr** [comment]
image

Added administrator icon to username display in the appbar -- should help a user know whether or not they are a standard user or not.

Certain topic actions such as delete were to be locked from general users... so adding the administrator ability was needed.

The first user to login becomes admin. Idea being, whoever sets this up for their community is 99% likely to be the community leader/owner anyhow. So it makes sense. They'll login to make sure stuff is working / setup before opening it up to general use.

Later we can add the ability for an admin to manage user roles

**Comment by JBraunsmaJr** [comment]
image
Added a dropdown navigational menu when user clicks on their username. 

- if user has the admin role the Admin Portal will appear
- Otherwise, by default the account item will appear

**Comment by JBraunsmaJr** [comment]
image

The admin dashboard has the ability to manage topics. Right now this is what the tabled view looks like.

- Noticing MudBlazor does not implement the same "concept" of pagination as originally thought. They paginate a list of items already available versus having it fetch content from external source.

## Added Scope
- Need to create a reusable pagination system which fetches data from our API.

**Comment by JBraunsmaJr** [comment]
# Pagination Progress

image
image
image

# Todo
- Need to figure out how to utilize Render Fragments so we can abstract this pagination component, make it even more reusable than reinventing the wheel every time
- Implement delete button functionality on the admin-topic page
- Add an edit/create topic section for admins as well

**Comment by JBraunsmaJr** [comment]
1. Didn't realize `@typeparam` was a valid directive in Blazor. This opened a lot of doors for us in terms of code reusability!
2. RenderFragments are our friends

**Comment by JBraunsmaJr** [comment]
# Breaking Changes
- Migrated from MySQL to Postgres. Required regenerating migrations. Will require developers to run the `reset-db` powershell script we have. (Good thing we have that right? lol)
- Added GraphQL for enabling us to consolidate queries. Granted we're newbies with it so might take some time to standardize / get it right.

**Comment by JBraunsmaJr** [comment]
- Got Pagination working with GraphQL endpoint now
- Updated pagination models to be on the client side -- considering custom endpoints from server are no longer needed in this regard
- Removed unused methods/views/classes
- Added TotalCount to GraphQL query for the topics.
- Fixed problem where TopicID was not provided downstream
- Fixed problem where, I think, where Background image for topic cards were not appearing
- GraphQL related stuff is source generated from the schema file located in the Client directory. I'm not 100% certain how this works with auto-updating considering the project runs together. So -- if updates are made schema wise, just copy it from Banana Cake Pop and paste it in there.

**Comment by JBraunsmaJr** [comment]
Showcasing admin topic view when a topic is accepting applicants
image

This is the dialog that is able to both edit and create topics
image

As an administrator on the admin portal, one can add/edit/delete topics.

**Pull request merged**
